// config.js

/**
 * A curated list of default symbols for initial scanning.
 * This list includes major indices and a broad selection of large, mid, and small-cap stocks
 * from the Indian market (NSE/BSE) to provide a comprehensive market overview.
 */
const defaultSymbols = new Set([
    // Indices
    '^NSEI', '^BSESN',

    // NIFTY 50 & Other Large Caps
    'RELIANCE.NS', 'TCS.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'INFY.NS', 'HINDUNILVR.NS', 'BHARTIARTL.NS', 'ITC.NS', 'SBIN.NS', 'LICI.NS',
    'BAJFINANCE.NS', 'KOTAKBANK.NS', 'HCLTECH.NS', 'LT.NS', 'MARUTI.NS', 'ASIANPAINT.NS', 'WIPRO.NS', 'AXISBANK.NS', 'ADANIENT.NS',
    'SUNPHARMA.NS', 'TITAN.NS', 'BAJAJFINSV.NS', 'ULTRACEMCO.NS', 'ONGC.NS', 'NESTLEIND.NS', 'NTPC.NS', 'M&M.NS', 'JSWSTEEL.NS', 'POWERGRID.NS',
    'TATAMOTORS.NS', 'ADANIPORTS.NS', 'COALINDIA.NS', 'TATASTEEL.NS', 'INDUSINDBK.NS', 'HINDALCO.NS', 'TECHM.NS', 'ADANIGREEN.NS', 'BAJAJ-AUTO.NS', 'GRASIM.NS',

    // Mid-Cap Selection
    'ADANIENSOL.NS', 'IOC.NS', 'VEDL.NS', 'PIDILITIND.NS', 'BPCL.NS', 'DLF.NS', 'SIEMENS.NS', 'SBILIFE.NS', 'HDFCLIFE.NS', 'GODREJCP.NS',
    'TATACONSUM.NS', 'HAVELLS.NS', 'AMBUJACEM.NS', 'INDIGO.NS', 'CHOLAFIN.NS', 'MARICO.NS', 'BANKBARODA.NS', 'PNB.NS', 'DABUR.NS', 'GAIL.NS',
    'BEL.NS', 'TVSMOTOR.NS', 'SRF.NS', 'SHREECEM.NS', 'ICICIPRULI.NS', 'BERGEPAINT.NS', 'JUBLFOOD.NS', 'MUTHOOTFIN.NS', 'TRENT.NS', 'HAL.NS', 'IDBI.NS',
    'BOSCHLTD.NS', 'SAIL.NS', 'NMDC.NS', 'IRCTC.NS', 'GLAND.NS', 'BANDHANBNK.NS', 'HINDZINC.NS', 'UPL.NS',

    // Small-Cap & Other Popular Stocks
    'YESBANK.NS', 'IDEA.NS', 'NHPC.NS', 'IRFC.NS', 'TATAPOWER.NS', 'PAYTM.NS', 'ZEEL.NS', 'IDFCFIRSTB.NS', 'IEX.NS', 'BHEL.NS',
    'DIXON.NS', 'AARTIIND.NS', 'DEEPAKNTR.NS', 'ASTRAL.NS', 'APOLLOTYRE.NS', 'BALKRISIND.NS', 'ESCORTS.NS', 'FORTIS.NS', 'LALPATHLAB.NS', 'M&MFIN.NS',
    'MANAPPURAM.NS', 'NATIONALUM.NS', 'PFC.NS', 'RBLBANK.NS', 'RECLTD.NS', 'SUZLON.NS', 'TRIDENT.NS', 'UNIONBANK.NS', 'VOLTAS.NS', 'JIOFIN.NS',

    // Expanded universe for deeper analysis
    'LTIM.NS', 'PERSISTENT.NS', 'COFORGE.NS', 'MPHASIS.NS', 'OFSS.NS', 'TATAELXSI.NS', 'INDIAMART.NS', 'AUBANK.NS', 'ICICIGI.NS', 'HDFCAMC.NS', 'ICICILOMB.NS', 'SHRIRAMFIN.NS', 'BAJAJHLDNG.NS', 'SBICARD.NS', 'ALKEM.NS', 'BIOCON.NS', 'GLENMARK.NS', 'IPCALAB.NS', 'LAURUSLABS.NS', 'ZYDUSLIFE.NS', 'METROPOLIS.NS', 'DMART.NS', 'PGHH.NS', 'GODREJPROP.NS', 'HINDCOPPER.NS', 'PAGEIND.NS', 'BATAINDIA.NS', 'RELAXO.NS', 'POLYCAB.NS', 'THERMAX.NS', 'SONACOMS.NS', 'CUMMINSIND.NS', 'ABB.NS', 'LTTS.NS', 'HONAUT.NS', 'ATGL.NS', 'AWL.NS', 'CONCOR.NS', 'PETRONET.NS', 'GMRINFRA.NS'
]);

/**
 * A set of symbols for stocks that are part of the Futures and Options (F&O) segment.
 * This is used by specific strategies that target high-volume, high-volatility stocks.
 */
const fnoSymbols = new Set([
    'ACC.NS', 'ADANIENT.NS', 'ADANIPORTS.NS', 'AMBUJACEM.NS', 'APOLLOHOSP.NS', 'APOLLOTYRE.NS', 'ASHOKLEY.NS', 'ASIANPAINT.NS', 'AUROPHARMA.NS', 'AXISBANK.NS', 'BAJAJ-AUTO.NS', 'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'BALKRISIND.NS', 'BANDHANBNK.NS', 'BANKBARODA.NS', 'BHEL.NS', 'BPCL.NS', 'BHARTIARTL.NS', 'BOSCHLTD.NS', 'BRITANNIA.NS', 'CANBK.NS', 'CHOLAFIN.NS', 'CIPLA.NS', 'COALINDIA.NS', 'COLPAL.NS', 'DABUR.NS', 'DIVISLAB.NS', 'DLF.NS', 'DRREDDY.NS', 'EICHERMOT.NS', 'ESCORTS.NS', 'FEDERALBNK.NS', 'GAIL.NS', 'GODREJCP.NS', 'GRASIM.NS', 'HCLTECH.NS', 'HDFCBANK.NS', 'HDFCLIFE.NS', 'HAVELLS.NS', 'HEROMOTOCO.NS', 'HINDALCO.NS', 'HINDPETRO.NS', 'HINDUNILVR.NS', 'ICICIBANK.NS', 'ICICIPRULI.NS', 'IDFCFIRSTB.NS', 'INDIGO.NS', 'INDUSINDBK.NS', 'INFY.NS', 'IOC.NS', 'IRCTC.NS', 'ITC.NS', 'JINDALSTEL.NS', 'JSWSTEEL.NS', 'JUBLFOOD.NS', 'KOTAKBANK.NS', 'L&TFH.NS', 'LT.NS', 'LUPIN.NS', 'M&M.NS', 'MARICO.NS', 'MARUTI.NS', 'MFSL.NS', 'MGL.NS', 'MUTHOOTFIN.NS', 'NATIONALUM.NS', 'NAUKRI.NS', 'NESTLEIND.NS', 'NMDC.NS', 'NTPC.NS', 'ONGC.NS', 'PAGEIND.NS', 'PEL.NS', 'PETRONET.NS', 'PFC.NS', 'PIDILITIND.NS', 'PNB.NS', 'POWERGRID.NS', 'RBLBANK.NS', 'RECLTD.NS', 'RELIANCE.NS', 'SAIL.NS', 'SBIN.NS', 'SHREECEM.NS', 'SIEMENS.NS', 'SRF.NS', 'SUNPHARMA.NS', 'SUNTV.NS', 'TATACHEM.NS', 'TATACONSUM.NS', 'TATAMOTORS.NS', 'TATAPOWER.NS', 'TATASTEEL.NS', 'TCS.NS', 'TECHM.NS', 'TITAN.NS', 'TORNTPHARM.NS', 'TRENT.NS', 'TVSMOTOR.NS', 'UBL.NS', 'ULTRACEMCO.NS', 'UPL.NS', 'VEDL.NS', 'VOLTAS.NS', 'WIPRO.NS', 'ZEEL.NS'
]);

// Ensure all F&O symbols are included in the default tracking universe so their data is always fetched.
fnoSymbols.forEach(symbol => defaultSymbols.add(symbol));

module.exports = {
    defaultSymbols,
    fnoSymbols
};